#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/eventcart_db
#    username: eventcart
#    password: eventcart123
#  redis:
#    host: redis
#    port: 6379
#  kafka:
#    bootstrap-servers: kafka:9092
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#   database-platform: org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventcart_db
    username: eventcart
    password: eventcart123
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


security:
  jwt:
    secret-key: 6b4c3b3d8f05c622d0cb9e019cb24b725107b907127a53363a3fe5a511650844
    expiration-time: 3600000