spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventcart_db
    username: eventcart
    password: eventcart123
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379

  kafka:
    # SADECE bootstrap-servers kullanın - consumer/producer içinde tekrar belirtmeyin
    bootstrap-servers: localhost:29092
    consumer:
      group-id: eventcart-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        # Connection timeout ayarları
        request.timeout.ms: 30000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
        max.poll.interval.ms: 300000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      properties:
        request.timeout.ms: 30000
        delivery.timeout.ms: 120000
        linger.ms: 0
        batch.size: 16384

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

# Detaylı logging
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
#    org.apache.kafka.clients: DEBUG
#    org.apache.kafka.common.network: DEBUG
#    com.eventcart: DEBUG

security:
  jwt:
    secret-key: 6b4c3b3d8f05c622d0cb9e019cb24b725107b907127a53363a3fe5a511650844
    expiration-time: 3600000